version: "3"
services:
  lease-version-reliability-test:
    image: lease-version-reliability-test:latest
    restart: on-failure:5
    environment:
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASS=${SNOWFLAKE_PASS}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_REGION=${SNOWFLAKE_REGION}
      - SNOWFLAKE_WH=${SNOWFLAKE_WH}
      - SNOWFLAKE_DB=${SNOWFLAKE_DB}
      - SNOWFLAKE_ML_USER=${SNOWFLAKE_ML_USER}
      - SNOWFLAKE_ML_PASS=${SNOWFLAKE_ML_PASS}
      - SNOWFLAKE_ML_ROLE=${SNOWFLAKE_ML_ROLE}
      - SNOWFLAKE_ML_ACCOUNT=${SNOWFLAKE_ML_ACCOUNT}
      - SNOWFLAKE_ML_REGION=${SNOWFLAKE_ML_REGION}
      - SNOWFLAKE_ML_DB=${SNOWFLAKE_ML_DB}
    command: ["sh", "-c", "python -m pytest"]

volumes:
  lease-version-relability-test:
