version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  python: circleci/python@2.1.1

executors:
  python:
    parameters:
      tag:
        type: string
        default: "3.9"
    docker:
      - image: cimg/python:<< parameters.tag >>

_defaults: &defaults
  machine:
    image: ubuntu-2004:202201-02
  working_directory: ~/repo

workflows:
  version: 2
  development:
    jobs:
      - pre-commit
      - aws-ecr/build-and-push-image:
          context: aws-deploy
          dockerfile: .docker/Dockerfile
          repo: compstak/lease-version-reliability
          tag: build-$CIRCLE_BUILD_NUM
          requires:
            - pre-commit

jobs:
  pre-commit:
    executor:
      name: python
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Combine precommit config and python versions for caching
          command: |
            cat .pre-commit-config.yaml > pre-commit-deps.txt
            python -VV >> pre-commit-deps.txt
      - restore_cache:
          keys:
            - v1-precommit-deps-{{ checksum "pre-commit-deps.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install pre-commit
            pre-commit install-hooks
      - save_cache:
          paths:
            - ~/.cache/pre-commit
            - ./venv
          key: v1-precommit-deps-{{ checksum "pre-commit-deps.txt" }}
      - run:
          name: Check code style using precommit
          command: |
            . venv/bin/activate
            pre-commit run --show-diff-on-failure --all-files
