attributes = [
    "tenant_name",
    "space_type_id",
    "transaction_size",
    "starting_rent",
    "execution_date",
    "commencement_date",
    "lease_term",
    "expiration_date",
    "work_value",
    "free_months",
    "transaction_type_id",
    "rent_bumps_percent_bumps",
    "rent_bumps_dollar_bumps",
    "lease_type_id",
]


data_type_dict = {
    "id": "int32",
    "submitter_person_id": "int32",
    "comp_data_id_version": "int32",
    "comp_data_id_master": "int32",
    "tenant_name_version": "string[pyarrow]",
    "space_type_id_version": "float64",
    "transaction_size_version": "float64",
    "starting_rent_version": "float64",
    "execution_date_version": "datetime64[ns]",
    "commencement_date_version": "datetime64[ns]",
    "lease_term_version": "float64",
    "expiration_date_version": "datetime64[ns]",
    "work_value_version": "float64",
    "free_months_version": "float64",
    "transaction_type_id_version": "float64",
    "rent_bumps_percent_bumps_version": "float64",
    "rent_bumps_dollar_bumps_version": "float64",
    "lease_type_id_version": "float64",
    "tenant_name_master": "string[pyarrow]",
    "space_type_id_master": "float64",
    "transaction_size_master": "float64",
    "starting_rent_master": "float64",
    "execution_date_master": "datetime64[ns]",
    "commencement_date_master": "datetime64[ns]",
    "lease_term_master": "float64",
    "expiration_date_master": "datetime64[ns]",
    "work_value_master": "float64",
    "free_months_master": "float64",
    "transaction_type_id_master": "float64",
    "rent_bumps_percent_bumps_master": "float64",
    "rent_bumps_dollar_bumps_master": "float64",
    "lease_type_id_master": "float64",
    "specialk_id": "string[pyarrow]",
}
